### ISSUE TITLE
Allow custom material front-matter to be more accessible in Fabricator templates

### ISSUE THREAD

**Issue by erikjung** [fbrctr/fabricator-assemble#9]
Currently, `parseMaterials()` [separates](https://github.com/fbrctr/fabricator-assemble/blob/master/index.js#L305) `notes` from the front-matter, treating them differently than other "custom" properties. They are available within the Fabricator templates as `{{notes}}`, but other properties are namespaced to the material. This makes it unclear how to lookup custom material data from the Fabricator templates.

An example use case:

You want to provide a list of documentation links specific to each material, and normalize the way they're displayed in the `includes/f-item.html` template.

```yml
notes: |
  These are notes associated with this `button` component.
external_docs:
  - url: http://example.com
    title: External Docs
  - url: http://example.com
    title: More External Docs
```

Accessing `external_docs` from within the Fabricator UI templates can apparently be done via `{{@root.material-name.external_docs}}`, but simply `{{external_docs}}` would be nicer.

I'm not sure if there is some possible combination of `@root` and `@key` that would provide the correct path without needing to explicitly reference the material name, but I was unable to find one. Using `{{@root.@key.foo}}` resulted in errors.

What if you could supply an array of keys to be relocated in the same way notes are?

```js
assemble({
  localDataIncludes: ['notes', 'external_docs']
});
```

Is it feasible to allow something like this to be passed along as an option to `assemble()`? The array of keys could also be used in `_.omit()` FWIW.
